session_name: fzmp
windows:
  - window_name: fzmp
    layout: main-horizontal
    panes:
    - shell_command:
      - fzmp -a; exit
      focus: true
    - shell_command:
      - mppcava -p ${HOME}/.config/mppcava/tmux.conf; exit
    options:
      main-pane-height: 20
