session_name: ${SESSION}
windows:
  - window_name: mpcplus
    focus: true
    panes:
    - shell_command:
      - mpcplus; exit
      focus: true
    - shell_command:
      - ${VIZCOMM}; exit
  - window_name: fzmp
    panes:
    - shell_command:
      - fzmp -a; exit
      focus: true
