directory: ~/Music
library: ~/.config/beets/musiclibrary.db

# Uncomment if you wish to place secret paths/tokens/credentials in
# ~/.config/beets/secrets.yaml
#
#include:
#   - secrets.yaml

import:
    copy: yes
    move: yes
    write: yes
    incremental: yes
    incremental_skip_later: yes
    quiet: no
    quiet_fallback: asis
    resume: yes
    from_scratch: no
    default_action: apply
    detail: yes
    non_rec_action: ask
    # duplicate_action can be 'skip', 'keep', 'remove', 'merge' or 'ask'
    duplicate_action: skip
    group_albums: no
    autotag: yes
    bell: no
    log: ~/.config/beets/import.log

plugins:
    - albumtypes
    - beetcamp
#   - convert
    - describe
#   - discogs
    - duplicates
    - edit
    - extrafiles
    - fromfilename
    - hook
    - importadded
    - info
    - lyrics
    - lastgenre
    - missing
    - mbsync
    - mpdstats
    - play
    - playlist
    - smartplaylist
    - mpdupdate
    - unimported

albumtypes:
    types:
        - ep: 'EP'
        - single: 'Single'
        - soundtrack: 'OST'
        - live: 'Live'
        - compilation: 'Anthology'
        - remix: 'Remix'
    ignore_va: compilation
    bracket: '[]'

bandcamp:
    include_digital_only_tracks: true
    search_max: 2
    art: no
    comments_separator: "\n---\n"
    exclude_extra_fields:
        - comments
#       - lyrics
    genre:
        capitalize: no
        maximum: 0
        always_include: []
        mode: progressive # classical, progressive or psychedelic

# Uncomment this and the convert plugin entry to enable format conversion
# of media in your Beets library with the 'beet convert' command
#
#convert:
#   dest: ~/Music/__Converted__
#   quiet: true
#   command: ffmpeg -i $source -y -vn -aq 2 $dest
#   extension: mp3

duplicates:
    album: yes
#   tiebreak:
#       items: [bitrate]

extrafiles:
    patterns:
        all: '*.*'

mpdstats:
    host: localhost
    port: 6600
    rating: yes
    rating_mix: 0.75

play:
    # The command used to open the playlist. Default: xdg-open
    # Insert $args to use the --args feature.
    #command: mpv $args --playlist
    command: mpc --quiet $args load 
    # If set, emit paths relative to this directory. Default: None.
    #relative_to: ~/Music
    # When using the -a option, the m3u will contain the paths to each track on
    # the matched albums. Enable this option to store paths to folders instead.
    # Default: no.
    #use_folders: no
    # Instead of creating a temporary m3u playlist and then opening it, simply
    # call the command with the paths returned by the query as arguments.
    # Default: no.
    raw: yes
    #  Set the minimum number of files to play which will trigger a warning to
    # be emitted. If set to no, warning are never issued. Default: 100.
    #warning_threshold: 100
    # Set whether or not a UTF-8 Byte Order Mark should be emitted into the m3u
    # file. If you’re using foobar2000 or Winamp, this is needed. Default: no.
    #bom: no

playlist:
  auto: yes
  playlist_dir: ~/.config/mpd/playlists
  relative_to: ~/Music

smartplaylist:
    relative_to: ~/Music
    playlist_dir: ~/.config/mpd/playlists
    forward_slash: no
    playlists:
        - name: 'rating.m3u'
          query: 'rating:0.4..1.0'

#       - name: 'not_played.m3u'
#         query: '-play_count: artist:'

#       - name: beatles.m3u
#         query: 'artist:Beatles'

        - name: 'ween.m3u'
          query: 'artist:Ween'

        - name: 1940s.m3u
          query: 'year:1940..1949'

        - name: 1950s.m3u
          query: 'year:1950..1959'

        - name: 1960s.m3u
          query: 'year:1960..1969'

        - name: 1970s.m3u
          query: 'year:1970..1979'

        - name: 1980s.m3u
          query: 'year:1980..1989'

        - name: 1990s.m3u
          query: 'year:1990..1999'

        - name: 2000s.m3u
          query: 'year:2000..2009'

        - name: 2010s.m3u
          query: 'year:2010..2019'

        - name: 2020s.m3u
          query: 'year:2020..2029'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::195(0|1|2|3|4|5|6|7|8|9)'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::196(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::197(0|1|2|3|4|5|6|7|8|9)'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::198(0|1|2|3|4|5|6|7|8|9)'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::199(0|1|2|3|4|5|6|7|8|9)'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::200(0|1|2|3|4|5|6|7|8|9)'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::201(0|1|2|3|4|5|6|7|8|9)'

#       - name: 'ReleasedIn$year.m3u'
#         query: 'year::202(0|1|2)'

mpd:
    host: localhost
    port: 6600
    rating: yes
    rating_mix: 0.75

# Uncomment this and the discogs plugin entry to enable Discogs metadata source
#
#discogs:
#   source_weight: 0.0
#   index_tracks: yes
#   user_token: Your_Discogs_User_Token

musicbrainz:
    # Default: 5
    # Higher: better for albums with many releases in many formats/countries
    # Lower: better for box sets
    #searchlimit: 10
    extra_tags: [year, catalognum, country, media, label]
    #genres: yes
#   Disable Musicbrainz: not in Beets 1.6.0, will be in 1.6.1
#   enabled: no

match:
    #strong_rec_thresh: 0.10
    #medium_rec_thresh: 0.25
    strong_rec_thresh: 0.075
    medium_rec_thresh: 0.125
    max_rec:
      unmatched_tracks: low
      missing_tracks: strong
    # The higher the weight, the lower the items go in the candidate list (greater
    # distance) when this penalty is applied.
    distance_weights:
      # Default: 3.0
      album: 6.0
      # Default: 3.0
      artist: 7.0
      # Default: 2.0
      totaltracks: 4.0
      # Default: 0.9
      missing_tracks: 1.0
      # Default: 0.6
      unmatched_tracks: 10.0
    #preferred:
    #    media: ['CD', 'Digital Media|File', 'Digital Media']
    #    countries: ['US', 'GB|UK']    
    preferred:
      countries: ['US', 'XW', 'GB|UK']
      media: ['Digital Media|File', 'CD']
    ignored_media:
      ['DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS']

paths:
    # Default paths configuration
    # default: $albumartist/$album%aunique{}/$track $title
    # singleton: Non-Album/$artist/$title
    # comp: Compilations/$album%aunique{}/$track $title
    default: "%if{$albumartist,$albumartist,%if{$artist,$artist,Unknown Artist}}/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title"
    singleton: "%if{$albumartist,$albumartist,%if{$artist,$artist,Unknown Artist}}/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title"
    comp: Compilations/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $artist - $title
    albumtype:soundtrack: Soundtracks/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes

threaded: no

unimported:
    ignore_extensions: jpg png
    ignore_subdirectories: data tmp

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

hook:
  hooks:
    - event: import_begin
      command: /usr/share/musicplayerplus/scripts/beet_log.sh Import begin
    - event: import
      command: /usr/share/musicplayerplus/scripts/beet_log.sh Import end

