directory: ~/Music
library: ~/.config/beets/musiclibrary.db

import:
    copy: no
    move: yes
    write: yes
    incremental: yes
    quiet: yes
    resume: yes
    from_scratch: yes
    default_action: apply
    detail: yes
    non_rec_action: ask
    duplicate_action: skip
    group_albums: no
    autotag: yes
    bell: no
    log: ~/.config/beets/import.log

plugins: duplicates edit fromfilename hook importadded info lyrics lastgenre missing mbsync mpdstats smartplaylist mpdupdate unimported

mpdstats:
    host: localhost
    port: 6600
    rating: yes
    rating_mix: 0.75

smartplaylist:
    relative_to: ~/Music
    playlist_dir: ~/.config/mpd/playlists
    forward_slash: no
    playlists:
        - name: 'rating.m3u'
          query: 'rating:0.4..1.0'

        - name: 'not_played.m3u'
          query: '-play_count: artist:'

        - name: beatles.m3u
          query: 'artist:Beatles'

        - name: 'dylan.m3u'
          query: 'artist:Dylan'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::195(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::196(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::197(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::198(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::199(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::200(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::201(0|1|2|3|4|5|6|7|8|9)'

        - name: 'ReleasedIn$year.m3u'
          query: 'year::202(0|1|2)'

mpd:
    host: localhost
    port: 6600
    rating: yes
    rating_mix: 0.75

match:
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.80
    medium_rec_thresh: 0.50
    max_rec:
        missing_tracks: medium
        #unmatched_tracks: medium
    preferred:
        #countries: ['GB|UK', 'US']
        media: ['CD', 'LP', 'Digital Media|File', 'Cassette']
        original_year: yes

paths:
    default: $albumartist/$year - $albumartist - $album%aunique{}/$track - $artist - $album - $title ($year)
    singleton: $artist/$artist - $album - $title ($year)
    comp: Compilations/$album%aunique{}/$track - $artist - $title ($year)

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes

unimported:
    ignore_extensions: jpg png
    ignore_subdirectories: data tmp

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

hook:
  hooks:
    - event: import_begin
      command: /usr/share/musicplayerplus/scripts/beet_log.sh Import begin
    - event: import
      command: /usr/share/musicplayerplus/scripts/beet_log.sh Import end

