directory: ~/Music
library: ~/.config/beets/library.db

import:
    copy: no
    incremental: yes
    quiet: yes
    log: ~/.config/beets/log.txt

plugins: fetchart lyrics lastgenre mpdstats

mpd:
    host: localhost
    port: 6600

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
