# MusicPlayerPlus ships with no plugins enabled that require secrets
# If you enable a plugin that requires secrets, place the plugin secret
# configuration in ~/.config/beets/secrets.yaml

#acoustid:
#  apikey: your_api_key

#discogs_extradata:
#  token: usertoken

#fetchart:
#  fanarttv_key: your_api_key

#follow:
#  email: your_email
#  password: seekrit
#  userid: your_user_id

#lastfm:
#  user: your-lastfm-username
#  api_key: your_api_key

#mbcollection:
#  collection: 'your-musicbrainz-collection-id'

musicbrainz:
#  user: your-musicbrainz-username
#  pass: 'your-musicbrainz-password'
