session_name: ${SESSION}
options:
  main-pane-height: ${MAIN_PANE_HEIGHT}
windows:
  - window_name: mpcplus
    focus: true
    panes:
    - shell_command:
      - mpcplus
      focus: true
    - shell_command:
      - mppcava -p ${HOME}/${MPCDIR}/cava-tmux.conf
  - window_name: fzmp
    panes:
    - shell_command:
      - fzmp -a
      focus: true
