name: C/C++ CI

on:
  push:
    paths:
      - 'mppcava/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update -y
    - name: upgrade
      run: sudo apt upgrade -y
    - name: install
      run: sudo apt install build-essentials libtool automake iniparser libncurses-dev libfftw3-dev -y
    - name: autogen
      run: ./autogen.sh
      working-directory: ./mppcava
    - name: configure
      run: ./configure --prefix=/usr
      working-directory: ./mppcava
    - name: make
      run: make
      working-directory: ./mppcava
