name: C/C++ CI

on:
  push:
    paths:
      - 'mpcplus/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mpcplus

    steps:
    - uses: actions/checkout@v2
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.2.0
      id: install-boost
      with:
        boost_version: 1.73.0
        platform_version: 20.04
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --prefix=/usr --enable-outputs --enable-clock --disable-visualizer --with-taglib
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: make
      run: make
